name: CI/CD

env:
  COMMIT-ID: ${{ github.sha }}
  CONTAINER-IMAGE-NAME: diamond-shop-api

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  build:
    name: Build Docker Image and Push to Digital Ocean Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Digital Ocean Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITALOCEAN_DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_DOCKER_REIGTRY_PASSWORD }}
          logout: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry.digitalocean.com/diamondshop/payment-gateway:${{ env.COMMIT-ID }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy to Digital Ocean Droplet
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DIGITALOCEAN_DROPLET_HOST }}
          username: ${{ secrets.DIGITALOCEAN_DROPLET_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_DROPLET_PASSWORD }}
          script: |
            docker stop $(docker ps -a | grep payment-gateway | awk '{print $1}')
            docker rm $(docker ps -a | grep payment-gateway | awk {'print $1'}) || true
            docker image rm $(docker images | grep payment-gateway | awk {'print $3'}) || true
            docker pull registry.digitalocean.com/diamondshop/payment-gateway:${{ env.COMMIT-ID }}
            docker run -d -p 8091:8080 --name payment-gateway registry.digitalocean.com/diamondshop/payment-gateway:${{ env.COMMIT-ID }}